import "./globals.css";
import "swiper/css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Menu } from "@/components/Menu";
import { AnimationProvider } from "@/providers/animationProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-[var(--secondary-bg)]`}
      >
        <Menu />
        <AnimationProvider>{children}</AnimationProvider>
      </body>
    </html>
  );
}
